### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by sarigs** [CheckPointSW/smart-console-extensions#13]
Dear Developer, 

 For readability and Search Engine Optimization (SEO) it would be great if you could do the followings:
- [x] Please provide more than 8 words in the "About" field

**Comment by chkp-rachel** [comment]
+Raz

**Comment by chkp-rachel** [comment]
Can you add Raz to all these mails please :)

**Comment by chkp-rachel** [comment]
An extension can use JavaScript to interact with SmartConsole. The interactions provide access to information, such as the extension location context, and can perform certain basic operations. For example, navigate to a rule. Interactions can return data asynchronously by matching callbacks.
