### ISSUE TITLE
Missing configured network assets to test connectivity with.

### ISSUE THREAD

**Issue by yurgers** [CheckPointSW/smart-console-extensions#16]
Good afternoon!
established a connection to check.

but when you start the window appears
There are no configured network resources for connection verification.

and I don't understand what needs to be done

![image](https://user-images.githubusercontent.com/31007640/92501767-a9760b80-f207-11ea-8e76-7b5e4f283728.png)

**Comment by chkp-roniz** [comment]
Hi @Yurgers ,
You need to first tag your network assets with **ConnectivityCheck** Tag.
You can do it in the window attached (by providing the exact object name) or by going to each object's editor and add the tag there.

**Comment by yurgers** [comment]
Yes, it worked
